### ISSUE TITLE
crash problem => cannot load bisect_app

### ISSUE THREAD

**Issue by GhostComputing** [knutin/bisect#2]
When I use bisect, I got an crash problem:

     {"init terminating in do_boot",{'cannot load',bisect_app,get_files}}

After my check, I found out  `bisect.app.src` cause the problem:

    ...
     {mod, { bisect_app, []}},
    ...

but the module `bisect_app` doesn't exist.

**Comment by knutin** [comment]
Just pushed 9dc56b0 which removes that line from `bisect.app.src`. It should not be needed as there's nothing to start up in the `bisect` app.

Thanks for letting me know!

**Comment by zyy17** [comment]
Thank you :+1:
